# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Downloads/Downloads/Notes/ENGG 3380/Lab 4 - ALU/Lab 4 - ALU.cache/wt} [current_project]
set_property parent.project_path {D:/Downloads/Downloads/Notes/ENGG 3380/Lab 4 - ALU/Lab 4 - ALU.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {d:/Downloads/Downloads/Notes/ENGG 3380/Lab 4 - ALU/Lab 4 - ALU.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Downloads/Downloads/Notes/ENGG 3380/Lab 4 - ALU/and_gate.vhd}
  {D:/Downloads/Downloads/Notes/ENGG 3380/Lab 4 - ALU/MUX31.vhd}
  {D:/Downloads/Downloads/Notes/ENGG 3380/Lab 4 - ALU/full_adder.vhd}
  {D:/Downloads/Downloads/Notes/ENGG 3380/Lab 4 - ALU/or_gate.vhd}
  {D:/Downloads/Downloads/Notes/ENGG 3380/Lab 4 - ALU/ALU.vhd}
  {D:/Downloads/Downloads/Notes/ENGG 3380/Lab 4 - ALU/ALU_16Bit.vhd}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top ALU_16Bit -part xc7a100tcsg324-1


write_checkpoint -force -noxdef ALU_16Bit.dcp

catch { report_utilization -file ALU_16Bit_utilization_synth.rpt -pb ALU_16Bit_utilization_synth.pb }
